### ISSUE TITLE
Release for integration

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-kratos#23]
The master branch is ready to be integrated with simphony-common 0.2.0, 0.2.1 and 0.2.2
@nathanfranklin, @roigcarlo, Could you make a release/tag please?
Thanks.

**Comment by nathanfranklin** [comment]
@roigcarlo , do you have time to make the release?

**Comment by roigcarlo** [comment]
I can make one in an hour more or less, is that ok?

**Comment by kitchoi** [comment]
@roigcarlo, sure!  Thanks so much!

**Comment by roigcarlo** [comment]
@kitchoi Ups sorry, I though we were in the Simphony common and I made the release there... 
I'm doing one for kratos now.

**Comment by roigcarlo** [comment]
@kitchoi The release has been made in the PR #24 and you can also find it in the release section. 
Sorry again for the mistake

**Comment by kitchoi** [comment]
@roigcarlo, That's great!  Thanks a lot!
